### ISSUE TITLE
Chords don't respect range

### ISSUE THREAD

**Issue by dbalatero** [eigenben/jazz_model#3]
If you want to eventually support MIDI playback, etc, it might be useful to start being more specific about the chord voicings. A voicing in the middle of the piano sounds really bad low. As well, some voicings lend themselves to being spread out on the keyboard (open voicings).

You could backfill this data for the chords you already have by assuming all your voicings were around middle C, and generating the specific C4/D4/E5-style notes appropriately.

**Comment by eigenben** [comment]
To me, a chord has nothing to do with range - it's a theoretical collection of tones devoid of any concept of octave.  So, for example: "Cmin7" is a chord.  The collection of specific pitches based on that chord comprises a voicing (for example the famed "so what" voicing of that chord).  So far I haven't done anything voicing-related (besides include the class in there), but I have plans on building this out and having a category of common voicings, at which time I'll definitely consider range.

**Comment by dbalatero** [comment]
Sure, if you separate chord and voicings as separate concepts, that would be fine.
